package common

var ProgrammingLanguages = map[string]string{
	"c" : "C",
	"cpp" : "C++",
	"csharp" : "C#",
	"clojure" : "Clojure",
	"codeql" : "CodeQL",
	"coffeescript" : "CoffeeScript",
	"dm" : "DM",
	"dart" : "Dart",
	"elixir" : "Elixir",
	"elm" : "Elm",
	"emacslisp" : "Emacs Lisp",
	"erlang" : "Erlang",
	"fsharp" : "F#",
	"fortran" : "Fortran",
	"go" : "Golang",
	"groovy" : "Groovy",
	"java" : "Java",
	"js" : "Javascript",
	"jinja" : "Jinja",
	"jsonnet" : "Jsonnet",
	"julia" : "Julia",
	"kotlin" : "Kotlin",
	"lean" : "Lean",
	"lua" : "Lua",
	"matlab" : "Matlab",
	"nix" : "Nix",
	"objectivec" : "Objective-C",
	"ocaml" : "OCaml",
	"perl" : "Perl",
	"php" : "PHP",
	"powershell" : "Powershell",
	"puppet" : "Puppet",
	"python" : "Python",
	"r" : "R",
	"roff" : "Roff",
	"ruby" : "Ruby",
	"rust" : "Rust",
	"scala" : "Scala",
	"scss" : "SCSS",
	"shell" : "Shell",
	"swift" : "Swift",
	"systemverilog" : "System Verilog",
	"typescript" : "Typescript",
	"vala" : "Vala",
	"verilog" : "Verilog",
	"vimscript" : "Vim script",
	"vbnet" : "Visual Basic .NET",
	"wasm" : "WebAssembly",
	"yaml" : "YAML",
}

var AlliedServices = map[string] string {
	"devops" : "DevOps",
	"documentation" : "Documentation",
	"sanitization" : "Code Sanitization",
	"test" : "Test Cases",
}

var ProjectType = map[string]string{
	"library_plugin" : "Library/Plugin",
	"database" : "Database",
	"webapp" : "Web Application",
	"mobileapp" : "Mobile Application", 
	"desktopapp" : "Desktop Application",
	"others" : "Others",
}

var Contributors = map[string]string{
	CONTRIBUTOR_COUNT[0] : "Project founder only",
	CONTRIBUTOR_COUNT[1] : "Less than 10",
	CONTRIBUTOR_COUNT[2] : "More than 10",
}