name: Unit Tests

on:
    pull_request:
        branches: ["master"]

env:
    GB_CLIENT_ID: ${{secrets.GB_CLIENT_ID}}
    GB_CLIENT_SECRET: ${{secrets.GB_CLIENT_SECRET}}
    GB_CONTRIBUTOR_REDIRECT_URI: ${{secrets.GB_CONTRIBUTOR_REDIRECT_URI}}
    GB_PROJECT_REDIRECT_URI: ${{secrets.GB_PROJECT_REDIRECT_URI}}
    SES_ACCESS_ID: ${{secrets.SES_ACCESS_ID}}
    SES_ACCESS_SECRET: ${{secrets.SES_ACCESS_SECRET}}
    SES_REGION: ${{secrets.SES_REGION}}
    SES_SENDER: ${{secrets.SES_SENDER}}
    MO_DATABASE: ${{secrets.MO_DATABASE}}
    MO_PORT: ${{secrets.MO_PORT}}
    MO_HOST: ${{secrets.MO_HOST}}
    MO_USER: ${{secrets.MO_USER}}
    MO_PASS: ${{secrets.MO_PASS}}
    MO_AUTH_METHOD: ${{secrets.MO_AUTH_METHOD}}
    MO_AUTH_DB: ${{secrets.MO_AUTH_DB}}

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v3
              with:
                  go-version: 1.18

            - name: Setup mongodb
              uses: supercharge/mongodb-github-action@1.7.0
              with:
                  mongodb-version: ${{ matrix.mongodb-version }}
                  mongodb-username: ${{secrets.MO_USER}}
                  mongodb-password: ${{secrets.MO_PASS}}
                  mongodb-db: supercharge

            - name: Build
              run: go build -v ./...

            - name: Test
              run: go test -v ./...
